#base-url: http://alexwendland.com/blog
base-url: /
name: Alex Wendland
title: Alex Wendland
description: Enjoy

markdown: kramdown
highlighter: rouge
permalink: /:year/:title/

safe: true
lsi: false

# TODO leverage https://github.com/envygeeks/jekyll-assets which is part of github-pages

