#base-url: http://alexwendland.com/blog
base-url: /
name: Alex Wendland
description: Enjoy

markdown: rdiscount
rdiscount:
    extensions: [smart]
highlighter: pygments
permalink: /:year/:title/

safe: true
lsi: false
