#base-url: http://alexwendland.com/blog
base-url: /
name: Alex Wendland
title: Alex Wendland
description: Enjoy

markdown: kramdown
highlighter: rouge
permalink: /:year/:title/

safe: true
lsi: false
